import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { Roboto } from 'next/font/google';
import { ThemeProvider } from '@mui/material/styles';
import theme from '../theme';
import { CopilotKit } from "@copilotkit/react-core";
import "@copilotkit/react-ui/styles.css";
import { Analytics } from "@vercel/analytics/react"
const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const COPILOT_CLOUD_PUBLIC_API_KEY = process.env.NEXT_PUBLIC_COPILOT_CLOUD_PUBLIC_API_KEY;
  return (
    <html lang="en">
     <body className={roboto.variable}>
     <CopilotKit publicApiKey={COPILOT_CLOUD_PUBLIC_API_KEY}>
      <Analytics/>
          <AppRouterCacheProvider>
           <ThemeProvider theme={theme}>
              {children}
         </ThemeProvider>
        </AppRouterCacheProvider>
        </CopilotKit>
      </body>
    </html>
  );
}
